config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    get 'withdrawal'
    get 'explanation'
    resources :relationships, only: [:create, :destroy]
    get 'relationships/following', as: 'following'
    get 'relationships/follower', as: 'follower'
    get 'relationships/mutual_follow', as: 'mutual_follow'
  end

  resources :posts do
    resources :post_comments, only: [:new, :edit, :create, :destroy, :update]
    resource :likes, only: [:create, :destroy]
  end

  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  resources :searchs, only: [:index]

  root 'homes#top'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  validates :comment, presence: true, length: { maximum: 120 }

  belongs_to :user
  belongs_to :post

  has_many :notifications, dependent: :destroy
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_post_comment, only: [:edit, :destroy, :update]

  def new
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.find(params[:id])
  end

  def create
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.new(post_comment_params)
    if @post_comment.save
      flash[:notice] = "投稿が完了しました！！"
      # コメントしたらnotificationsテーブル(通知モデル)に保存
      @notification_post = @post_comment.post
      @notification_post.create_notification_comment(current_user, @post_comment.id)
      redirect_to post_path(@post)
    else
      flash[:alert] = "投稿できませんでした！"
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.find(params[:id])
    PostComment.find_by(post_id: @post.id, id: @post_comment.id).destroy
    flash[:notice] = "投稿を削除しました！！"
    redirect_to post_path(@post)
  end

  def update
    @post = Post.find(params[:post_id])
    @post_comment = PostComment.find(params[:id])
    if @post_comment.update(post_comment_params)
      flash[:notice] = "更新が完了しました！！"
      redirect_to post_path(@post)
    else
      flash[:alert] = "更新ができませんでした！"
      render :edit
    end
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:user_id, :post_id, :comment).merge(user_id: current_user.id, post_id: @post.id)
  end

  def correct_post_comment
    post_comment = PostComment.find(params[:id])
    unless post_comment.user.id == current_user.id
      flash[:alert] = "あなたの編集ページではありません！"
      redirect_to posts_path
    end
  end
end

app/views/post_comments/_index.html.erb
<div class="col-sm-12 col-lg-8">
  <%= link_to 'コメントを投稿する', new_post_post_comment_path(post.id), class: "btn btn-light far fa-comment-dots my-1 p-2" %>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th></th>
        <th>コメント</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <!--コメント内容を一覧表示するためeach文を使用-->
      <% post_comments.each do |post_comment|%>
        <tr>
          <td>
            <%= link_to user_path(post_comment.user.id) do%>
              <%= attachment_image_tag post_comment.user, :image, size: '50x50', format: 'jpeg', fallback: asset_path('no_image2.jpeg'), class: 'rounded-circle'%>
            <% end %>
          </td>
          <td>
            <p class="text-break"><%= safe_join(post_comment.comment.split("\n"), tag(:br)) %></p>
          </td>
          <td class="text-center">
            <% if post_comment.user.id == current_user.id %>
              <%= link_to '編集', edit_post_post_comment_path(post_comment.post.id, post_comment.id), class: 'btn btn-success' %>
              <%= link_to '削除', post_post_comment_path(post_comment.post.id, post_comment.id), method: :delete,
              data:{confirm: "本当に削除しますか？"}, class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate post_comments %>
</div>

app/views/post_comments/edit.html.erb
<% provide(:title, "コメント編集")%>
<div class="comment-edit container my-5">
  <div class="mee-post col-sm-10 col-lg-6 mx-auto  shadow p-5">
    <h3>コメント編集ページ</h3>
    <!--編集したコメント内容を送信するためのフォーム-->
    <%= form_with model: [@post, @post_comment], local: true do |f|%>
      <div class="form-group">
        <%= f.label :comment, 'コメント(120文字まで)'%>
        <%= f.text_area :comment, class: 'form-control', id: 'input-text-comment', size: '30x5' %>
        <p class="text-right" id="counter-comment">残り120文字</p>
      </div>
      <%= f.submit '更新する', class: 'btn btn-outline-success' %>
    <% end %>
  </div>
</div>

app/views/post_comments/new.html.erb
<% provide(:title, "コメント投稿")%>
<div class="container mt-5">
  <div class="mee-post col-sm-10 col-lg-7 mx-auto shadow p-5">
    <h3>コメント投稿ページ</h3>
    <!--コメント内容を送信するため-->
    <%= form_with model: [@post, @post_comment], local: true do |f| %>
      <div class="form-group">
        <%= f.label :comment, 'コメント(120文字まで)'%>
        <%= f.text_area :comment, class: 'form-control', id: 'input-text-comment', :placeholder => "コメントを入力してください", size: '30x5' %>
        <p class="text-right" id="counter-comment">残り120文字</p>
      </div>
      <div>
        <%= f.submit '投稿する', class: 'btn btn-outline-success' %>
      </div>
    <% end %>
  </div>
  <div class="row comment-cautions mt-4">
    <div class="comment-texts mt-3 p-1">
      <h4 class="font-weight-bold mt-4 pl-1">使用する上で…</h4>
      <ol>
        <li class="comment-exsample my-5">利用している方が不快に思わないコメントを送りましょう！</li>
        <li class="comment-exsample my-5">メッセージは必ず入力しましょう！(空白だと送信されません)</li>
        <li class="comment-exsample">利用していただいてありがとうございます！</li>
      </ol>
    </div>
    <div class="comment-image mt-5"></div>
  </div>
</div>