config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    get 'withdrawal'
    get 'explanation'
    resources :relationships, only: [:create, :destroy]
    get 'relationships/following', as: 'following'
    get 'relationships/follower', as: 'follower'
    get 'relationships/mutual_follow', as: 'mutual_follow'
  end

  resources :posts do
    resources :post_comments, only: [:new, :edit, :create, :destroy, :update]
    resource :likes, only: [:create, :destroy]
  end

  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  resources :searchs, only: [:index]

  root 'homes#top'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :visitor, class_name: 'User', optional: true
  belongs_to :visited, class_name: 'User', optional: true

  belongs_to :post, optional: true
  belongs_to :post_comment, optional: true

  belongs_to :room, optional: true
  belongs_to :message, optional: true

  scope :sort_desc, -> { order(created_at: :desc) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    # 現在ログインしているユーザー宛の通知情報を取得
    # その際に自分が自分に通知を送ることになったものは取得せず、降順で並び替えて取得
    @notifications = current_user.visiteds.where.not(visitor_id: current_user.id).sort_desc.page(params[:page]).per(6)

    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  # 自分宛に送られた通知を削除するルーティング
  def destroy
    user = User.find(params[:id])
    notifications = Notification.where(visited_id: user.id)
    notifications.each do |notification|
      notification.destroy
    end
    flash[:alert] = "通知を全て削除しました！"
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  # 現在ログインしているユーザー宛の通知でcheckedカラムがfalseの通知を取得
  def unchecked_notifications
    current_user.visiteds.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<tr>
  <td>
    <p class="d-inline-block">
      <%= link_to notification.visitor.nickname, user_path(notification.visitor.id),
      class: 'who-nickname font-weight-bold text-decoration-none text-dark rounded-sm' %>さんが
    </p>
    <!--notificationsテーブル(通知モデル)のactionカラムの値で処理を分岐-->
    <% if notification.action == "follow" %>
      <p class="d-inline-block">あなたをフォローしました！</p>
    <% elsif notification.action == "like"%>
      <p class="d-inline-block">
        <%= link_to 'あなたの投稿', post_path(notification.post.id),
        class: 'you-post text-decoration-none font-weight-bold text-dark rounded-sm' %>にいいねしました！
      </p>
    <% elsif notification.action == "post_comment" %>
      <!--投稿したユーザーのIDと通知を送るユーザーのIDが等しかった場合-->
      <% if notification.post.user.id == notification.visited.id%>
        <!--等しかった場合、あなたの投稿にコメントしたと通知-->
        <p class="d-inline-block">
          <%= link_to 'あなたの投稿', post_path(notification.post.id),
          class: 'you-post text-decoration-none font-weight-bold text-dark rounded-sm' %>にコメントしました！
        </p>
      <% else %>
        <!--自分がコメントした投稿に新しくコメントがついた場合の通知-->
        <p class="d-inline-block">
          <%= link_to notification.post.user.nickname, post_path(notification.post.id),
          class: 'you-post text-decoration-none font-weight-bold text-dark rounded-sm' %>さんの投稿にコメントしました！
        </p>
      <% end %>
      <div class="opacity">
        <%= notification.post_comment.comment %>
      </div>
    <% elsif notification.action == 'chat_room'%>
      <p class="d-inline-block">あなたとチャットを開始しました！</p>
    <% elsif notification.action == 'chat_message' %>
      <p class="d-inline-block">
        <%= link_to 'チャットルーム', room_path(notification.room.id),
        class: 'you-post text-decoration-none font-weight-bold text-dark rounded-sm' %>内にメッセージを送信しました！
      </p>
      <div class="opacity">
        <%= safe_join(notification.message.body.split("\n"), tag(:br)) %>
      </div>
    <% end %>
    <p class="text-right"><%= time_ago_in_words(notification.created_at).upcase %>前</p>
  </td>
</tr>

app/views/notifications/index.html.erb
<% provide(:title, "通知一覧")%>
<div class="container my-5 notifications">
  <div class="col-sm-12 col-lg-9 mx-auto">
    <h3><i class="fas fa-bell text-secondary"></i> 通知一覧ページ</h3>
    <!--@notificationsの中身が空じゃなかったら通知削除ボタンを表示-->
    <% unless @notifications.blank? %>
      <%= link_to '通知を全て削除する', notification_path(current_user.id), method: :delete,
      class: 'text-decoration-none', data:{confirm: "本当に削除しますか？" } %>
    <% end %>
    <%= paginate @notifications %>
    <table class="table table-bordered shadow">
      <tr>
        <thead class="thead-dark">
          <th></th>
        </thead>
      </tr>
      <tbody>
        <!--通知があるか、ないかで処理分岐-->
        <% if @notifications.exists? %>
          <%= render @notifications %>
        <% else %>
          <tr>
            <td>
              <p>通知はありません</p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>