config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    get 'withdrawal'
    get 'explanation'
    resources :relationships, only: [:create, :destroy]
    get 'relationships/following', as: 'following'
    get 'relationships/follower', as: 'follower'
    get 'relationships/mutual_follow', as: 'mutual_follow'
  end

  resources :posts do
    resources :post_comments, only: [:new, :edit, :create, :destroy, :update]
    resource :likes, only: [:create, :destroy]
  end

  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  resources :searchs, only: [:index]

  root 'homes#top'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  validates :first_name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 20 }
  validates :nickname, presence: true, length: { maximum: 20 }
  validates :introduction, length: { maximum: 350 }

  # postモデルとのアソシエーション
  has_many :posts, dependent: :destroy
  # post_commentモデルとのアソシエーション(中間テーブル)
  has_many :post_comments, dependent: :destroy
  # likeモデルとのアソシエーション(中間テーブル)
  has_many :likes, dependent: :destroy

  # relationshipモデルとのアソシエーション(フォローした側の情報取得)(中間テーブル)
  has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following_user, through: :follower, source: :followed

  # relationshipモデルとのアソシエーション(フォローされた側の情報取得)(中間テーブル)
  has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :follower_user, through: :followed, source: :follower

  # entryモデルとのアソシエーション(中間テーブル)
  has_many :entries, dependent: :destroy
  # messageモデルとのアソシエーション(中間テーブル)
  has_many :messages, dependent: :destroy

  # notificationモデルとのアソシエーション(通知モデル)(中間テーブル)(通知送った側の情報取得)
  has_many :visitors, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :notificationing_user, through: :visitors, source: :visited

  # notificationモデルとのアソシエーション(通知モデル)(中間テーブル)(通知送られた側の情報取得)
  has_many :visiteds, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :notificationer_user, through: :visiteds, source: :visitor

  # フォロー作成メゾット
  def follow(user)
    follower.create(followed_id: user.id)
  end

  # フォロー削除メゾット
  def unfollow(user)
    follower.find_by(followed_id: user.id).destroy
  end

  # フォロー確認メゾット
  def following_user?(user)
    following_user.include?(user)
  end

  # 相互フォロー取得メゾット
  def mutual_follow
    following_user & follower_user
  end

  # フォロー通知作成メゾット
  def create_notification_follow(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ?", current_user.id, id, 'follow'])
    # インスタンス変数tempに値と言えるものがなければレコード作成
    if temp.blank?
      notification = current_user.visitors.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # 検索メゾット(User)
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(nickname: content).order(created_at: :desc)
    elsif method == 'forward'
      User.where('nickname LIKE ?', content + '%').order(created_at: :desc)
    elsif method == 'backward'
      User.where('nickname LIKE ?', '%' + content).order(created_at: :desc)
    else
      User.where('nickname LIKE ?', '%' + content + '%').order(created_at: :desc)
    end
  end

  # ソートメゾット
  def self.sort_for(sort)
    if sort == 'new'
      User.order(created_at: :desc).where.not(admin: true)
    elsif sort == 'old'
      User.order(created_at: :asc).where.not(admin: true)
    else
      User.order(created_at: :desc).where.not(admin: true)
    end
  end

  # ゲストユーザー作成・探すメゾット
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.first_name = 'ゲスト'
      user.last_name = 'ゲスト'
      user.nickname = 'ゲスト'
      user.password = SecureRandom.urlsafe_base64
      user.introduction = 'ゲストユーザーです'
      user.admin = true
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # 新規登録後のリダイレクト先
  def after_sign_up_path_for(resource)
    user_explanation_path(current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # ゲストユーザーのメゾット
  def guest_sign_in
    # ゲストユーザーを作成・特定している
    user = User.guest
    # ここで新規登録とログインしている(deviseのメゾット)
    sign_in user
    flash[:notice] = "ゲストユーザーとしてログインしました！！"
    redirect_to user_path(user.id)
  end

  # ログイン後の遷移先
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    sort = params[:sort]
    @users = User.sort_for(sort).page(params[:page]).per(12)
  end

  def show
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page]).per(8)
    # ajaxをする際に使用
    @follow = Relationship.find_by(follower_id: current_user.id, followed_id: @user.id)

    # チャットルーム関連の部分
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless current_user.id == @user.id
      @current_user_entry.each do |current|
        @user_entry.each do |user|
          if current.room_id == user.room_id
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新が完了しました!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "更新ができませんでした！"
      render :edit
    end
  end

  def withdrawal
    @user = User.find(params[:user_id])
  end

  def destroy
    user = User.find(params[:id])
    entries = Entry.where(user_id: user.id)
    # 退会ユーザーがチャットルームを作成していた場合、退会と同時にチャットルームを削除
    # entriesに値がある場合のみ、処理を実行
    if entries.present?
      entries.each do |entry|
        entry.room.destroy
      end
    end
    user.destroy
    flash[:notice] = "退会しました！ またのご利用をお待ちしております！！"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :image, :introduction)
  end

  def correct_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      flash[:alert] = "権限がありません！"
      redirect_to users_path
    end
  end
end

app/views/users/_introduction.html.erb
<table class="table table-bordered">
  <tbody class="thead-dark">
    <tr>
      <th>ニックネーム</th>
      <td class="text-break text-monospace"><%= user.nickname %></td>
    </tr>
    <tr>
      <th>自己紹介</th>
      <!--自己紹介が設定されていなかった場合で条件分岐-->
      <% if @user.introduction.blank? %>
        <td class="text-break text-monospace">自己紹介を設定しよう！！</td>
      <% else %>
        <td class="text-break text-monospace"><%= safe_join(user.introduction.split("\n"), tag(:br)) %></td>
      <% end %>
    </tr>
    <tr>
      <th>登録日時</th>
      <td class="text-break text-monospace"><%= user.created_at.to_s(:datetime_jp) %></td>
    </tr>
    <tr>
      <th>更新日時</th>
      <td class="text-break text-monospace"><%= user.updated_at.to_s(:datetime_jp) %></td>
    </tr>
  </tbody>
</table>

app/views/users/_list.html.erb
<!--ユーザーを一覧で表示するためeach文を使用-->
<% users.each do |user| %>
  <div class="col-sm-6 col-lg-4 text-center mx-auto">
    <div class="card border-dark mb-3">
      <div class="users1">
        <%= link_to user_path(user.id), class: 'text-decoration-none' do %>
          <%= attachment_image_tag user, :image, size: '350x350', format: 'jpeg', fallback: asset_path('no_image2.jpeg'), class: 'bd-placeholder-img card-img-top' %>
          <div class="mask1">
            <div class="caption1">ユーザー詳細ページへ！！</div>
          </div>
        <% end %>
      </div>
      <p class="text-left text-body card-header"><%= user.nickname %></p>
      <div class="card-body">
        <% if user.introduction.blank? %>
          <p class="text-truncate text-left card-text">自己紹介を設定しよう！！</p>
        <% else %>
          <p class="text-truncate text-left card-text"><%= user.introduction %></p>
        <% end %>
        <p class="text-right card-text"><%= time_ago_in_words(user.created_at).upcase %>前</p>
        <%= link_to user_path(user.id), class: 'text-decoration-none' do %>
          <p class="font-weight-bold text-dark text-right">詳細ページへ！<i class="fas fa-angle-double-right"></i></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー編集")%>
<div class="user-edit container my-5">
  <div class="mee-user col-sm-10 col-lg-7 mx-auto mx-auto shadow p-5">
    <h3><i class="fas fa-edit text-secondary"></i>編集ページ</h3>
    <div>
      <%= form_with model: @user, local: true do |f|%>
        <div class="form-group pt-3">
          <%= f.label :nickname, 'ニックネーム' %>
          <%= f.text_field :nickname, class: 'form-control w-75' %>
        </div>
        <div class="form-group pt-3">
          <%= f.label :image, '画像' %>
          <%= f.attachment_field :image, class: 'form-control-file' %>
        </div>
        <div class="form-group pt-3">
          <%= f.label :introduction, 'プロフィール文(350字まで)' %>
          <%= f.text_area :introduction, class: 'form-control', id: 'input-text', size: '30x10' %>
          <p class="text-right" id="counter">残り350文字</p>
        </div>
        <div class="row mx-auto">
          <div class="pt-4">
            <%= f.submit '更新する', class: 'btn btn-outline-success' %>
          </div>
          <div class="ml-auto pt-4">
            <%= link_to '退会する？', user_withdrawal_path(current_user.id), class: 'btn btn-outline-danger' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/explanation.html.erb
<!--会員登録後の設定手順-->
<div class="explanations container pt-5">
  <div class="row explanation-lists">
    <div class="explanations-list col-lg-8">
      <h2><%= current_user.nickname %> さん会員登録ありがとうございます！</h2>
      <h4 class="pl-3">登録後のおすすめ手順をご紹介します！！！</h4>
      <div class="pl-4">
        <h5><i class="fas fa-check-circle"></i>自己紹介を設定してみよう</h5>
        <p class="explanation-text">
          最初の設定のままでは、<br>
          <span class="mee-color">Mee</span>を利用している方々にあなたの<span class="charm-color">魅力</span>が伝わりません！<br>
          ぜひとも設定しましょう！
        </p>
      </div>
      <div class="pl-4">
        <h5><i class="fas fa-check-circle"></i>投稿にコメント・いいねしてみよう</h5>
        <p class="explanation-text">
          <span class="mee-color">Mee</span>には良い投稿がたくさんあります！<br>
          緊張するかもしれませんが、<span class="active-color">積極的</span>にやっていきましょう！
        </p>
      </div>
      <div class="pl-4">
        <h5><i class="fas fa-check-circle"></i>投稿してみよう</h5>
        <p class="explanation-text">
          記念すべき<span class="first-post-color">最初の投稿</span>をしましょう！<br>
          きっと多くの方がコメントしてくれるはずです！
        </p>
      </div>
      <div class="text-center mb-1">
        <%= link_to 'さぁMeeの世界へ！', user_path(current_user.id), class: "btn btn-primary btn-lg"%>
      </div>
    </div>
    <div class="col-lg-3 mt-5">
      <div class="explanation-image"></div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧")%>
<div class="container my-4">
  <h3><i class="fas fa-users text-secondary"></i> ユーザー一覧</h3>
  <div class="form-group">
    <%= form_with url: users_path, method: :get, remote: true do |f| %>
    <div class="row">
      <div class="col-6 col-md-3">
        <%= f.select :sort, options_for_select({'登録日時が新しい順'=>'new', '登録日時が古い順'=>'old'}), { include_blank: '選択してください'}, class: 'form-control' %>
      </div>
      <%= f.submit '検索', class: 'btn btn-light' %>
    </div>
    <% end %>
  </div>
  <div id="users_index" class="row">
    <%= render 'users/list', users: @users %>
  </div>
  <%= paginate @users %>
</div>

app/views/users/index.js.erb
$("#users_index").html("<%= j(render 'users/list', users: @users)%>")

app/views/users/show.html.erb
<% provide(:title, "ユーザー詳細&いいね一覧")%>
<div class="container my-5">
  <div class="row">
    <div class="col-md-6 col-lg-5 mx-auto">
      <h3 class="mt-2"><i class="fas fa-user-edit text-secondary"></i> ユーザー詳細ページ</h3>
      <div class="card border-dark">
        <%= attachment_image_tag @user, :image, size: '350x350', format: 'jpeg', fallback: asset_path('no_image2.jpeg'), class: 'card-img-top' %>
        <p class="card-header"><%= @user.nickname %></p>
        <div class="card-body text-center">
          <p class="card-text d-inline-block"><%= link_to 'フォロー一覧', user_following_path(@user), class: "btn btn-primary" %></p>
          <p class="card-text d-inline-block"><%= link_to 'フォロワー一覧', user_follower_path(@user), class: "btn btn-primary" %></p>
          <p class="card-text"><%= link_to '相互フォロー一覧', user_mutual_follow_path(@user), class: "btn btn-primary" %></p>
        </div>
        <div class="card-footer text-center">
          <% if current_user == @user %>
            <%= link_to '編集する', edit_user_path(@user), class: "fas fa-edit btn btn-outline-success" %>
          <% else %>
            <div id="follow_<%= @user.id %>">
              <%= render 'relationships/follow_btn', user: @user, follow: @follow %>
            </div>
          <% end %>
          <div class="chat_<%= @user.id %>">
            <%= render 'rooms/chat_room', is_room: @is_room, room_id: @room_id, room: @room, entry: @entry, user: @user %>
          </div>
        </div>
      </div>
    </div>
    <!--自己紹介部分-->
    <div class="col-md-12 col-lg-7 mt-5">
      <%= render 'users/introduction', user: @user %>
    </div>
    <!--いいね一覧部分-->
    <div id="likes_<%= @user.id%>" class="col-md-12 mt-3">
      <%= render 'likes/index', likes: @likes %>
    </div>
  </div>
</div>

app/views/users/withdrawal.html.erb
<!--退会確認画面-->
<% provide(:title, "退会確認")%>
<div class="withdrawal container mt-5">
  <div class="col-md-12 mx-auto">
    <h3 class="text-center"><%= @user.nickname %>さん、本当に退会しますか？</h3>
    <p class="text-center mt-5">
      <%= link_to '退会する', user_path(current_user.id), method: :delete, class: 'btn btn-danger btn-lg' %>
    </p>
  </div>
  <div class="withdrawal-image mx-auto"></div>
</div>