config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    get 'withdrawal'
    get 'explanation'
    resources :relationships, only: [:create, :destroy]
    get 'relationships/following', as: 'following'
    get 'relationships/follower', as: 'follower'
    get 'relationships/mutual_follow', as: 'mutual_follow'
  end

  resources :posts do
    resources :post_comments, only: [:new, :edit, :create, :destroy, :update]
    resource :likes, only: [:create, :destroy]
  end

  resources :rooms, only: [:show, :create] do
    resources :messages, only: [:create, :destroy]
  end

  resources :notifications, only: [:index, :destroy]

  resources :searchs, only: [:index]

  root 'homes#top'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="bg-dark">
  <p class="text-center text-white">© Mee. All rights reserved.</p>
  <div class="container">
    <div class="footer-item">
      <%= link_to '会社概要', root_path, class: 'text-decoration-none text-white pb-3' %>
      <%= link_to '利用規約', root_path, class: 'text-decoration-none text-white pb-3' %>
      <%= link_to 'お問い合わせ', root_path, class: 'text-decoration-none text-white pb-3' %>
      <% if current_user.try(:admin?)%>
        <%= link_to '管理者ページへ', rails_admin_path, class: 'text-decoration-none text-white pb-3' %>
      <% end %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to root_path, class: 'site-logo col-12 col-md-6 col-lg-1' do %>
        <%= image_tag 'logo.png', size: '100x100'%>
      <% end%>
      <!--画面サイズを小さくなった場合、ナビゲーションリンクを表示-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="ml-auto">
          <ul class="navbar-nav nav-lists">
            <!--ログインしているかどうかでヘッダーの内容を変更-->
            <% if user_signed_in? %>
              <%= link_to user_path(current_user), class: 'nav-link'  do %>
                <%= attachment_image_tag current_user, :image, format: 'jpeg', fallback: asset_path('no_image2.jpeg'), size: '50x50', class: 'rounded-circle' %>
              <% end %>
              <li class="nav-item">
                <%= link_to 'ユーザー一覧', users_path, class: 'fas fa-users header-users nav-link text-decoration-none px-2'%>
              </li>
              <li class="nav-item">
                <%= link_to ' 投稿一覧', posts_path, class: 'fas fa-list header-posts nav-link font-weight-bold text-decoration-none px-2'%>
              </li>
              <%= link_to  notifications_path, class: 'header-notification nav-list nav-link text-decoration-none' do %>
                <!--通知あったら円が右下にあるようにif文で条件分岐させてある-->
                <% if unchecked_notifications.any? %>
                  <p class="n-circle rounded-circle px-1"><%= unchecked_notifications.count %></p>
                <% end %>
                  <li class="far fa-bell header-notifications nav-item px-2 font-weight-bold"> 通知一覧</li>
              <% end %>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete,
                class: 'fas fa-sign-out-alt header-sign_out nav-link text-decoration-none px-2'%>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to ' 新規登録', new_user_registration_path, class: 'fas fa-user header-new nav-link text-decoration-none px-3'%>
              </li>
              <li class="nav-item">
                <%= link_to ' ログイン', new_user_session_path, class: 'fas fa-sign-in-alt header-login nav-link text-decoration-none px-3'%>
              </li>
            <% end %>
          </ul>
        </div>
        <!--ログインしていれば検索フォーム表示-->
        <% if user_signed_in? %>
          <div class="form-group mt-1">
            <%= form_with url: searchs_path, method: :get, local: true do |f| %>
              <%= f.text_field :content, :placeholder => "ユーザー名、投稿タイトルを入力", class: 'form-control form-control-sm w-100' %>
              <%= f.select :model, options_for_select({'ユーザー名'=>'user', '投稿タイトル'=>'post'}), class: 'form-control' %>
              <%= f.select :method, options_for_select({'完全一致'=>'perfect', '前方一致'=>'forward', '後方一致'=>'backward', '部分一致'=>'partial'}),
              class: 'form-control' %>
              <%= f.submit '検索', class: 'btn btn-secondary btn-sm'%>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>

     <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <%= favicon_link_tag %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <!--サクセスメッセージ＆警告文-->
    <% if flash[:alert] %>
      <h6 class="alert alert-danger font-weight-bold mb-0"><%= alert %></h6>
    <% elsif flash[:notice]%>
      <h6 class="alert alert-success font-weight-bold mb-0"><%= notice %></h6>
    <% end %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>